ai_context_version: 1.1

# Dieses Repo ist Teil des Heimgewebes.
# Systemweiter Kontext durch Heimgeist:
#   metarepo/ai-contexts/heimgeist.ai-context.yml

system_context:
  heimgeist: "../metarepo/ai-contexts/heimgeist.ai-context.yml"

project:
  name: aussensensor
  summary: Scripted data collection pushing events to chronik.
  role: sensor_event_producer
  primary_language: bash
  visibility: internal

heimgewebe:
  axis:
    - Events
    - Motorik
    - Contracts
  fleet:
    enabled: true
  wgx:
    profile_expected: true
    guard_smoke_expected: true

interfaces:
  consumes:
    - "event.schema"
  produces:
    - "aussen.event.*"

contracts:
  schemas:
    - path: "contracts/aussen.event.schema.json"
      note: "Read-only mirror of canonical schema."

dependencies:
  internal:
    - name: chronik
      relationship: uses
      interface:
        - http_ingest_aussen
    - name: contracts
      relationship: uses
      interface:
        - json_schema_selfcheck
  external:
    - name: curl
    - name: jq

architecture:
  entrypoints:
    - scripts/*.sh
  key_paths:
    - path: lib/validation.sh
      purpose: local JSON/JSONL validation before send
  data_flow:
    input: polling / external sensors
    processing: map to contract shape
    output: POST to chronik ingest

boundaries:
  not_responsible_for:
    - "Event storage (chronik does that)"
    - "Visualizing data (leitstand does that)"
  dangerous_assumptions:
    - "Assuming chronik is always available (must retry)"

conventions:
  branching: "main, feature/*"
  commit_prefix: "aussensensor"
  ci_platform: github_actions

documentation:
  runbook: docs/runbook.md

ai_guidance:
  do:
    - validate JSON before sending to avoid noisy ingest failures
    - implement retries with exponential backoff
  dont:
    - send partial or multiline JSONL entries
